version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple-bank
  
  redis:
    image: redis:7-alpine
    
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
      - "9090:9090"
    environment:
      MODE: production
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]