

data_source:
  driver: postgres
  source: postgresql://root:secret@postgres:5432/simple-bank?sslmode=disable

server:
  http:
    host: 0.0.0.0
    port: 8002
  grpc:
    host: 0.0.0.0
    port: 9090

jwt:
  secret: r439r743c89rbv436c942v36e123v9c46231e32ecbt53t
  access_token_duration: 15m
  refresh_token_duration: 24h